- name: Disable systemd-resolved
  systemd:
    name: systemd-resolved
    enabled: false
    state: stopped

- name: Remove resolve.conf symlink
  file:
   path: "/etc/resolv.conf"
   state: absent
  changed_when: false

- name: Create /etc/resolv.conf
  template:
    dest: /etc/resolv.conf
    src: etc/resolv.conf.j2
    mode: 0644
  changed_when: false
