---
- name: dnsmasq | Install
  package:
    name: dnsmasq
    state: present

- name: set /etc/resolv.conf
  copy:
    dest: /etc/resolv.conf
    content: |
      nameserver 127.0.0.1

- name: create /etc/resolv.dnsmasq
  template:
    src: etc/resolv.dnsmasq.j2
    dest: /etc/resolv.dnsmasq
  notify: restart dnsmasq

- name: create /etc/dnsmasq.conf
  template:
    src: etc/dnsmasq.conf
    dest: /etc/dnsmasq.conf
  notify: restart dnsmasq

  # The dnsmasq service is already started when installed via a package
  # manager. It is required to restart the service to ensure that the
  # service uses the proper configuration file.
- name: start and enable dnsmasq
  systemd:
    daemon_reload: true
    name: dnsmasq
    state: restarted
    enabled: true
  changed_when: false
