---
- name: Install dnsmasq
  package:
    name: dnsmasq
    state: present

- name: Create dnsmasq group
  group:
    name: "{{ dnsmasq_group }}"
    state: present

- name: Create dnsmasq pid file
  file:
    group: dnsmasq
    owner: dnsmasq
    path: /run/dnsmasq/dnsmasq.pid
    state: file
  when: ansible_os_family == "Debian"

- name: Create dnsmasq user
  user:
    create_home: false
    group: "{{ dnsmasq_group }}"
    name: "{{ dnsmasq_user }}"
    state: present
    system: true

- name: Create /etc/dnsmasq.conf
  template:
    backup: true
    dest: /etc/dnsmasq.conf
    src: etc/dnsmasq.conf
  notify:
    - restart dnsmasq

- name: Create /etc/resolv.dnsmasq
  template:
    dest: /etc/resolv.dnsmasq
    src: etc/resolv.dnsmasq.j2
  notify:
    - restart dnsmasq

  # The dnsmasq service is already started when installed via a package
  # manager. It is required to restart the service to ensure that the
  # service uses the proper configuration file.
- name: Enable and start dnsmasq
  systemd:
    daemon_reload: true
    enabled: true
    name: dnsmasq
    state: restarted
  changed_when: false

- name: Check if dhclient configuration exists
  stat:
    path: /etc/dhcp/dhclient.conf
  register: result

- name: Configure the default DNS resolver as a fallback option
  blockinfile:
    block: supersede domain-name-servers 127.0.0.1, 169.254.169.253;
    insertafter: EOF
    path: /etc/dhcp/dhclient.conf
    state: present
  when: result.stat.exists

- name: Apply changes to dhclient
  command: dhclient
  changed_when: false
  ignore_errors: true
  when: result.stat.exists

- name: Disable systemd-resolved if needed
  include_tasks: disable-systemd-resolved.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version is version("18", "==")
