---
dependency:
  name: galaxy
driver:
  name: ec2
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ubuntu1804
    image: ami-0a4f4704a9146742a
    instance_type: t2.small
    vpc_subnet_id: subnet-0fdf330139d3de49f
provisioner:
  log: true
  name: ansible
verifier:
  name: testinfra
