---
dependency:
  name: galaxy
driver:
  name: ec2
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ubuntu1804
    image: ami-0a4f4704a9146742a
    instance_type: t2.small
    ssh_username: ubuntu
    vpc_subnet_id: subnet-0fdf330139d3de49f
  - name: rhel8
    image: ami-098bb5d92c8886ca1
    instance_type: t2.small
    ssh_username: ec2-user
    vpc_subnet_id: subnet-0fdf330139d3de49f
  - name: arch-linux
    image: ami-01d988fc8ed4684e6
    instance_type: t2.small
    ssh_username: arch
    vpc_subnet_id: subnet-0fdf330139d3de49f
provisioner:
  log: true
  name: ansible
verifier:
  name: testinfra
