---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - command: /sbin/init
    image: ppc64le/centos:8
    name: instance
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: testinfra
