jobs:
  test:
    name: molecule test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install required dependencies
        run: pip install -r requirements.txt
      - name: Enable execution of different multi-architecture containers
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          EC2_REGION: '${{ secrets.EC2_REGION }}'
        run: molecule test --all
name: Molecule Test
'on':
  - push
  - pull_request
